### PR TITLE
Use OGGM Docker Image instead of conda environment

### PR DESCRIPTION
**Pull request by fmaussion**
Just to keep track of changes and merge later

### CODE REVIEW

**Comment by TimoRoth** [comment]
This seems to be working now, and I think I added all packages the conda image has.

Only real downside is the quite substantial increase in image size. Up from ~1.5GB to over 4GB.
This is mostly down to Docker-Stupidity: jupyterhub/r2d requires that the Python-Env is user writable.
For that, the Dockerfile has to chmod it. And Docker in turn copies the entirety of the chmodded files into a new layer. ~2GB of extra image size just caused by that...

**Comment by TimoRoth** [comment]
For reference: This needs https://github.com/jupyterhub/repo2docker/pull/1097 to work.

**Comment by fmaussion** [comment]
> Only real downside is the quite substantial increase in image size. Up from ~1.5GB to over 4GB.

That's actually quite a downside :-( I was wondering why it took so much time to lauch mybinder yesterday, and now I think that's the reason... Is there absolutely no way around this? This is almost a deal-breaker for me (maybe not for oggm-hub but for mybinder at least...)

**Comment by TimoRoth** [comment]
On 22.11.2021 17:14, Fabien Maussion wrote:
>     Only real downside is the quite substantial increase in image size.
>     Up from ~1.5GB to over 4GB.
> 
> That's actually quite a downside :-( I was wondering why it took so much 
> time to lauch mybinder yesterday, and now I think that's the reason... 
> Is there absolutely no way around this? This is almost a deal-breaker 
> for me (maybe not for oggm-hub but for mybinder at least...)

I've already tried to implement an improvement. By not using chmod, but 
creating venvs in the users homedir instead.
Images for that are currently cooking, so we'll see soon.

Other than that, the biggest increase in image size is caused by docker 
duplicating a bunch of stuff, and not being smart enough to deduplicate it.
That's a LONG (open since 2016) standing issue with Docker, that has 
never been resolved: https://github.com/moby/moby/issues/21950

**Comment by TimoRoth** [comment]
Seems like this is just a difference in how Github and Docker Hub display image sizes.
Github shows on-disk image size, which is ~6GB.
Docker Hub shows download size. Which for the old image is ~1.5GB, and for the new image, after I got rid of the chmod, is ~1.1GB. With the chmod still in, it was ~1.6GB.

**Comment by fmaussion** [comment]
@TimoRoth how does this look like now that https://github.com/jupyterhub/repo2docker/pull/1097 is merged? Can you push this again to see if it builds properly? I'd like to see if latest master works on it, and if we can adress the rioxarray change

**Comment by TimoRoth** [comment]
There's still no release with it, but I have prepped our hub to support it, so it's fine to go in my book.

**Comment by TimoRoth** [comment]
What I just realized... Merging this will probably make this stop working on myBinder and the like, until they switch to a version of repo2docker with the just merged PRs in.

Edit: Nevermind, I forgot they just pull, and don't build...

**Comment by fmaussion** [comment]
@TimoRoth r2d is released including your patch: https://github.com/jupyterhub/repo2docker/blob/2022.02.0/docs/source/changelog.rst 

Anything that needs changing here? Otherwise I'll merge

**Comment by TimoRoth** [comment]
On 14.02.2022 16:21, Fabien Maussion wrote:
> @TimoRoth <https://github.com/TimoRoth> r2d is released including your 
> patch: 
> https://github.com/jupyterhub/repo2docker/blob/2022.02.0/docs/source/changelog.rst 
> <https://github.com/jupyterhub/repo2docker/blob/2022.02.0/docs/source/changelog.rst>
> 
> Anything that needs changing here? Otherwise I'll merge

No, fine to merge for all I'm aware.

**Pull request merged**
